version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 14
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
      - npm install typescript
  build:
    commands:
      - echo starting build ...
      - npm run build
  post_build:
    commands:
      - echo build completed

      
artifacts:
  files:
    - '**/*'
    - appspec.yml