version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 14
  pre_build:
    run-as: ec2-user
    commands:
      - echo installing dependencies...
      - npm install
      - npm install tsc
  build:
    run-as: ec2-user
    commands:
      - echo starting build ...
      - tsc
  post_build:
    run-as: ec2-user
    commands:
      - echo build completed

artifacts:
  files:
    - dist/